version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - cyclop # unnecessary
    - depguard # unnecessary
    - dupl # unnecessary
    - funlen # unnecessary
    - goconst # unnecessary
    - godot # unnecessary
    - godox # unnecessary
    - interfacebloat # unnecessary
    - ireturn # NOTE: too many false positives and negatives occur frequently, causing the --fix option to malfunction. So it is disabled.
    - lll # unnecessary
    - nlreturn # ignore "return with no blank line before"
    - noinlineerr # if err := ...; err != nil { return err }
    - nonamedreturns # unnecessary
    - varnamelen # unnecessary
    - wsl # ignore "declarations should never be cuddled"
    - wsl_v5 # unnecessary
  settings:
    revive:
      rules:
        - name: empty-block
          disabled: true
    wrapcheck:
      ignore-sigs:
        - func errors.New(text string) error
        - func fmt.Errorf(format string, a ...any) error
        - func fmt.Errorf(format string, a ...interface{}) error
        - func github.com/hakadoriya/z.go/errorz.Errorf(format string, a ...interface{}) error
        - func (context.Context).Err() error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - canonicalheader
          - containedctx
          - cyclop
          - dupl
          - dupword
          - err113
          - exhaustruct
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - maintidx
          - noctx
          - revive
          - staticcheck
          - testpackage
          - unused
          - varnamelen
          - wrapcheck
        path: _test\.go
      - linters:
          - revive
        path: internal/.*\.go # Ignore only internal because not exported
        text: should have its own declaration
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hakadoriya/secretenv
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
